name: "facile_tf_nov2"
platform: "tensorflow_savedmodel"
max_batch_size : 16000
#dynamic_batching {
#   preferred_batch_size: [ 10000 ]
#}
input [
  {
    name: "continuousinputs"
    data_type: TYPE_FP32
    dims: [ 10 ]
  },
  {
    name: "ieta"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "depth"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
instance_group [
  {
    kind: KIND_GPU,
    count: 10
  }
]
#optimization { execution_accelerators {
#  gpu_execution_accelerator : [ {
#    name : "tensorrt"
#    parameters { key: "precision_mode" value: "FP32" }
#    parameters { key: "max_workspace_size_bytes" value: "1073741824" }
#    }]
#}}
