name: "identity_fp32"
backend: "identity"
max_batch_size: 20
#dynamic_batching { 
# preferred_batch_size : 10 
# max_queue_delay_microseconds: 50000
#}
input [
  {
    name: "input"
    data_type: TYPE_UINT32
    dims: [ 200000 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_INT8
    dims: [ -1 ]
    #dims: [ 2036649 ]                                                                                                                                                                                                                        
  }
]
instance_group [
  {
    count: 1
    kind : KIND_CPU

  }
]


