name: "identity_fp32"
backend: "identity"
max_batch_size: 1
input [
  {
    name: "input"
    data_type: TYPE_UINT32
    dims: [ 200000 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_INT8
    #dims: [ 7200000 ]
    dims: [ -1 ]
  }
]
instance_group [
  {
    count: 1
    kind : KIND_GPU

  }
]


